---
title: "Untitled"
author: "abbey yatsko"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
```

load data
```{r}
ALS_30m_0 <- read.csv("split0/ALS_30m_0.csv")
CNN_30m_0 <- read.csv("split0/CNN_30m_0.csv")

ALS_30m_1 <- read.csv("split1/ALS_30m_1.csv")
CNN_30m_1 <- read.csv("split1/CNN_30m_1.csv")

ALS_30m_46 <- read.csv("split46/ALS_30m_46.csv")
CNN_30m_46 <- read.csv("split46/CNN_30m_46.csv")

ALS_30m_51 <- read.csv("split51/ALS_30m_51.csv")
CNN_30m_51 <- read.csv("split51/CNN_30m_51.csv")

tony_outputs_original <- read.csv("tony_output_original.csv")
tony_outputs_far <- read.csv("tony_output_far.csv")

tony_outputs <- rbind(tony_outputs_original, tony_outputs_far)
```

clean error metrics calculated by ab and jed
```{r}
# split 0: join ALS_10m_0 and ALS_20m_0 by 'id' 
split0_30m <- left_join(ALS_30m_0, CNN_30m_0)
names(split0_30m)[names(split0_30m) == "ALS_30m_0mean"] <- "ALS"
names(split0_30m)[names(split0_30m) == "CNN_30m_0mean"] <- "CNN"
split0_30m$grid <- "30"
split0_30m$split <- "0"
split0_30m$person <- "ab"

# get rid of fid, left, top, right, bottom
split0_30m <- split0_30m[, -c(1, 3, 4, 5, 6, 7, 8)]

# split 1: join ALS_10m_1 and ALS_20m_1 by 'id' 
split1_30m <- left_join(ALS_30m_1, CNN_30m_1)
names(split1_30m)[names(split1_30m) == "ALS_30m_1mean"] <- "ALS"
names(split1_30m)[names(split1_30m) == "CNN_30m_1mean"] <- "CNN"
split1_30m$grid <- "30"
split1_30m$split <- "1"
split1_30m$person <- "ab"

# get rid of fid, left, top, right, bottom
split1_30m <- split1_30m[, -c(2, 3, 4, 5, 6, 7)]

# split 46 (test data is far away): join ALS_10m_1 and ALS_20m_1 by 'id' 
split46_30m <- left_join(ALS_30m_46, CNN_30m_46)
names(split46_30m)[names(split46_30m) == "ALS_30m_46mean"] <- "ALS"
names(split46_30m)[names(split46_30m) == "CNN_30m_46mean"] <- "CNN"
split46_30m$grid <- "30"
split46_30m$split <- "46"
split46_30m$person <- "ab"

# get rid of fid, left, top, right, bottom
split46_30m <- split46_30m[, -c(1, 3, 4, 5, 6, 7, 8)]

# split 51 (test data is far away, only one block): join ALS_10m_1 and ALS_20m_1 by 'id' 
split51_30m <- left_join(ALS_30m_51, CNN_30m_51)
names(split51_30m)[names(split51_30m) == "ALS_30m_51mean"] <- "ALS"
names(split51_30m)[names(split51_30m) == "CNN_30m_51mean"] <- "CNN"
split51_30m$grid <- "30"
split51_30m$split <- "51"
split51_30m$person <- "ab"

# get rid of fid, left, top, right, bottom
split51_30m <- split51_30m[, -c(1, 3, 4, 5, 6, 7, 8)]

# rbind split0_10m and split0_20m
test1 <- rbind(split0_30m, split1_30m, split46_30m, split51_30m)
```

clean error metrics calculated by tony 
```{r}
# filter tony_outputs to only include name = all_train_test_splits_test_0 and name = all_train_test_splits_test_1
tony_split1_2_46 <- tony_outputs[tony_outputs$name == "all_train_test_splits_test_0" | tony_outputs$name == "all_train_test_splits_test_1" | tony_outputs$name == "Distance_blocks_Test_46" | tony_outputs$name == "Distance_blocks_Test_51", ]
tony_split1_2_46$split <- sub(".*_(\\d+)$", "\\1", tony_split1_2_46$name)
tony_split1_2_46$grid <- 30

# select columns fid, predition_mean, ground_truth_mean
tony <- tony_split1_2_46[, c("fid", "ground_truth_mean", "prediction_mean", "grid", "split")]
names(tony)[names(tony) == "fid"] <- "id"
names(tony)[names(tony) == "ground_truth_mean"] <- "ALS"
names(tony)[names(tony) == "prediction_mean"] <- "CNN"
tony$person <- "tony"

# rbinding test1 and tony
test1 <- rbind(test1, tony)
```

initial visualization
```{r}
# (a) Scatterplot of ALS vs CNN
ggplot(test1, aes(x = ALS, y = CNN)) +
  geom_point(alpha = 0.05) +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +  # Add a reference line
  labs(title = "",
       x = "Observed ALS",
       y = "Predicted CNN") +
  facet_wrap(split~person, ncol = 2)+
  xlim(0,10)+
  ylim(0,10)+
  theme_minimal()
```

calculate residuals and error metrics
```{r}
test1 <- test1 %>%
  mutate(residuals = ALS - CNN)

test1 <- na.omit(test1)

# Create height bins (3m bins, from 0 to 30m)
test1 <- test1 %>%
  mutate(height_class = cut(ALS, breaks = seq(0, 30, by = 3), include.lowest = TRUE))

# Function to calculate the metrics
calculate_metrics <- function(df) {
  n <- nrow(df)
  mae <- mean(abs(df$ALS - df$CNN), na.rm = TRUE)
  rmse <- sqrt(mean((df$ALS - df$CNN)^2, na.rm = TRUE))
  mbe <- mean(df$CNN - df$ALS, na.rm = TRUE)
  r2 <- summary(lm(CNN ~ ALS, data = df))$r.squared
  r <- cor(df$ALS, df$CNN, use = "complete.obs")
  
  return(c(MAE = mae, RMSE = rmse, MBE = mbe, R2 = r2, Pearson_R = r))
}

# Group by height classes and calculate the metrics for each class
metrics_by_class <- test1 %>%
  group_by(split, height_class, person) %>% # remove height_class if you want to calculate for the whole dataset
  summarise(MAE = mean(abs(ALS - CNN), na.rm = TRUE),
            RMSE = sqrt(mean((ALS - CNN)^2, na.rm = TRUE)),
            MBE = mean(CNN - ALS, na.rm = TRUE),
            R2 = summary(lm(CNN ~ ALS))$r.squared,
            Pearson_R = cor(ALS, CNN, use = "complete.obs"))

# View the resulting table
print(metrics_by_class, n = 26)
```

```{r}
# Reshape the metrics_by_class to long format
metrics_long <- metrics_by_class %>%
  pivot_longer(cols = c(MAE, RMSE, MBE), 
               names_to = "Metric", 
               values_to = "Value")

# Plot the metrics using ggplot
ggplot(metrics_long, aes(x = Metric, y = Value, fill = person)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_viridis_d() +  # Use viridis color palette
  labs(title = "Error Metrics by Height Class",
       x = "Error metric", 
       y = "Error (m)", 
       fill = "Metric") +
  facet_wrap(split~height_class, scales = "free", ncol = 3)+
  theme_minimal()

# plot of counts by each size cleass interval 
ggplot(test1, aes(x = height_class)) +
  geom_bar(fill = "blue") +
  labs(title = "Counts by Height Class",
       x = "Height Class (m)",
       y = "Count") +
  facet_wrap(~grid)+
  theme_minimal()
```

```{r}
save.image("Metrics.RData")
```

