---
title: "Untitled"
author: "abbey yatsko"
date: "2024-10-11"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(here)
library(sf)
library(readr)
```

*code is not working. use as template only* 

extract data from model output geopackages
```{r}
input_folder <- "/Volumes/BAMspace/6_staff_folders/Abbey/multiscale_lidar_ms/output_files/CNN/run1_zonal_stats"

gpkg_files <- list.files(input_folder, pattern = "\\.gpkg$", full.names = TRUE)

# Read all attribute tables into a list
attribute_tables <- lapply(gpkg_files, function(file) {
  # Read GeoPackage
  gpkg_data <- st_read(file)
  
  # Convert to a data frame
  as.data.frame(gpkg_data)
})

# Assign names to the list based on file names
names(attribute_tables) <- tools::file_path_sans_ext(basename(gpkg_files))
                                                     
# combine all attribute tables into one data frame
outputs <- do.call(rbind, attribute_tables)

# calculate shade volume from height sums by multiplying each value by 0.5m*0.5m = 0.25m (units = m3)
outputs$prediction_sum_sv <- outputs$prediction_sum * 0.25
outputs$ground_truth_sum_sv <- outputs$ground_truth_sum * 0.25
```

Calculate error metrics 
```{r}
# Group by height classes and calculate the metrics for the whole dataset
metrics_all <- outputs %>%
  group_by(fold_name) %>% # remove height_class if you want to calculate for the whole dataset
  summarise(MAE = mean(abs(ground_truth_sum_sv - prediction_sum_sv), na.rm = TRUE),
            RMSE = sqrt(mean((ground_truth_sum_sv - prediction_sum_sv)^2, na.rm = TRUE)),
            MBE = mean(prediction_sum_sv - ground_truth_sum_sv, na.rm = TRUE), # pos = overest, neg = underest
            R2 = summary(lm(prediction_sum_sv ~ ground_truth_sum_sv))$r.squared,
            mean_observed = mean(ground_truth_sum_sv), 
            MAE_p = MAE / mean_observed, 
            RMSE_p = RMSE / mean_observed, 
            MBE_p = MBE / mean_observed, 
            MAE_p_inv = 1- MAE_p, # interpret as percentage accuracy
            RMSE_p_inv = 1 - RMSE_p, # low values mean the model is more accurate
            MBE_p_inv = 1 - MBE_p) 

metrics_all <- as.data.frame(metrics_all)
```

Visualization
```{r}
# convert to long format by height class
metrics_long_all <- metrics_all %>%
  pivot_longer(cols = c(RMSE_p, R2, MAE_p, MBE_p), 
               names_to = "Metric", 
               values_to = "Value")

ggplot(metrics_long_all, aes(x = Metric, y = Value, fill = Metric)) +
  geom_boxplot() +  # Change to boxplo
  labs(title = "Mean Error Metrics for 25 Folds",
       x = "", 
       y = "Error") +
  facet_wrap(~Metric, scales = "free", ncol = 2) +  # Facet by Metric
  theme_minimal() +
  scale_fill_brewer(palette = "Blues") +
  theme(legend.position = "none",  strip.text = element_blank())


# density plot to compare ALS and CNN model
# group by name, calculate average of ground truth and prediction
outputs_fold_mean <- outputs %>%
  group_by(fold_name) %>%
  summarise(prediction_fold_mean = mean(prediction_sum_sv, na.rm = TRUE),
            ground_truth_fold_mean = mean(ground_truth_sum_sv, na.rm = TRUE))

outputs_long <- outputs[, c("prediction_sum_sv", "ground_truth_sum_sv", "fold_name")]

# merge outputs_long with outputs_fold_mean
outputs_long <- merge(outputs_long, outputs_fold_mean, by = "fold_name", all.x = TRUE)

outputs_long <- pivot_longer(outputs_long, cols = c("prediction_sum_sv", "ground_truth_sum_sv"), names_to = "indexes", values_to = "values")

# for each fold
ggplot(outputs_long, aes(x = values, fill = indexes, group = indexes)) +  
  theme_bw() +
  labs(x = "Shade Volume", y = "Frequency") +
  guides(fill = guide_legend(title = "Indexes"),  # Keep the fill legend
         color = "none") +  # Remove the color legend
  facet_wrap(~fold_name) +  
  scale_fill_manual(values = c("#7b6f89", "#FFDB58"), labels = c("Ground truth ALS", "CNN modeled")) + 
  scale_color_manual(values = c("#7b6f89", "#FFDB58", "#7b6f89", "#FFDB58"), 
                     labels = c("Ground truth ALS", "CNN modeled", "Ground truth ALS", "CNN modeled")) + 
  geom_density(aes(y = ..density.., fill = indexes, color = indexes), inherit.aes = TRUE, alpha = 0.6) + 
  geom_vline(aes(xintercept = prediction_fold_mean, color = "CNN modeled"), linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = ground_truth_fold_mean, color = "Ground truth ALS"), linetype = "dotted", size = 1) + 
  theme(axis.title = element_text(size = 14, face = "bold", color = "gray20"), 
        axis.text.x.bottom = element_text(size = 14), 
        axis.text.y = element_text(size = 14), 
        legend.direction = "horizontal", 
        legend.position = "bottom", 
        legend.title = element_text(size = 14, face = "bold"), 
        legend.text = element_text(size = 14), 
        title = element_text(size = 14), 
        panel.spacing = unit(1, "lines"), 
        strip.text = element_text(size = 12))

# all folds together
prediction_fold_mean <- mean(outputs_fold_mean$prediction_fold_mean, na.rm = TRUE)
ground_truth_fold_mean <- mean(outputs_fold_mean$ground_truth_fold_mean, na.rm = TRUE)

ggplot(outputs_long, aes(x = values,  fill = indexes)) +  
  theme_bw() +
  labs(x = "Shade Volume", y = "Frequency") +
  geom_density(aes(y = ..density.., fill = indexes), inherit.aes = TRUE, alpha=.6) +
  #geom_vline(aes(xintercept = 2.029173), color = "#FFDB58", linetype = "dashed", size = 1) +
 # geom_vline(aes(xintercept = 2.029006), color = "#7b6f89", linetype = "dotted", size = 1) +
  scale_fill_manual(values = c("#7b6f89", "#FFDB58"), 
                     labels = c("Ground truth ALS", "CNN modeled")) +
  theme(axis.title = element_text(size = 14, face = "bold", color = "gray20"),
        axis.text.x.bottom = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        title = element_text(size = 14),
        panel.spacing = unit(1, "lines"),
        strip.text = element_text(size = 12))
```

Summary of metrics
```{r}
# Calculate the mean for each numeric column (excluding the first)
means <- colMeans(metrics_all[, -1], na.rm = TRUE)

# Calculate the standard deviation for each numeric column (excluding the first)
sds <- apply(metrics_all[, -1], 2, sd, na.rm = TRUE)

# Create a tibble with means and standard deviations as rows
results_tibble <- tibble(
  Statistic = c("Mean", "Standard Deviation"),
  MAE = c(means["MAE"], sds["MAE"]),
  RMSE = c(means["RMSE"], sds["RMSE"]),
  MBE = c(means["MBE"], sds["MBE"]),
  R2 = c(means["R2"], sds["R2"]),
  MAE_p = c(means["MAE_p"], sds["MAE_p"]),
  RMSE_p = c(means["RMSE_p"], sds["RMSE_p"]),
  MBE_p = c(means["MBE_p"], sds["MBE_p"])
)

print(results_tibble)
```

Weighted error by fold
```{r}
# weighted error calculation 
alpha <- 1/3  # Weight for MAE
beta <- 1/3   # Weight for RMSE
gamma <- 1/3  # Weight for R²

metrics_all <- metrics_all %>%
  group_by(fold_name) %>%
  mutate(
    Raw_Weight = alpha * MAE_p_inv + beta * RMSE_p_inv + gamma * R2
  )

# plot to make sure it makes sense - there should be a strong correlation between higher R2 and weight
ggplot(metrics_all, aes(x = R2, y = Raw_Weight)) +
  geom_point() + 
  theme_classic()

# there should be a strong correlation between higher RMSE and weight
ggplot(metrics_all, aes(x = RMSE_p_inv, y = Raw_Weight)) +
  geom_point() + 
  theme_classic()

# there should be a strong correlation between higher MAE and weight
ggplot(metrics_all, aes(x = MAE_p_inv, y = Raw_Weight)) +
  geom_point() + 
  theme_classic()

# export as csv
# write.csv(metrics_all, "data/data_out/metrics_all.csv", row.names = FALSE)
```

Error by height classes
```{r}
# Create height bins (3m bins, from 0 to 30m)
outputs <- outputs %>%
  mutate(height_class = cut(ground_truth_mean, breaks = seq(0, 30, by = 3), include.lowest = TRUE))

# Group by height classes and calculate the metrics for each class
metrics_by_hclass <- outputs %>%
  group_by(fold_name, height_class) %>% 
  summarise(MAE = mean(abs(ground_truth_sum_sv - prediction_sum_sv), na.rm = TRUE),
            RMSE = sqrt(mean((ground_truth_sum_sv - prediction_sum_sv)^2, na.rm = TRUE)),
            MBE = mean(prediction_sum_sv - ground_truth_sum_sv, na.rm = TRUE), # pos = overest, neg = underest
            R2 = summary(lm(prediction_sum_sv ~ ground_truth_sum_sv))$r.squared,
            mean_observed = mean(ground_truth_sum_sv), 
            MAE_p = MAE / mean_observed, 
            RMSE_p = RMSE / mean_observed, 
            MBE_p = MBE / mean_observed, 
            MAE_p_inv = 1- MAE_p, # interpret as percentage accuracy
            RMSE_p_inv = 1 - RMSE_p, # low values mean the model is more accurate
            MBE_p_inv = 1 - MBE_p) 

# convert to long format by height class
hclass_metrics_long <- metrics_by_hclass %>%
  pivot_longer(cols = c(RMSE_p, R2, MAE_p, MBE_p), 
               names_to = "Metric", 
               values_to = "Value")

# visualization: error by height class
ggplot(hclass_metrics_long, aes(x = height_class, y = Value, fill = height_class)) +
  geom_boxplot() +  # Change to boxplot
  scale_fill_viridis_d() +  # Use viridis color palette
  labs(title = "Error Metrics by Height Class",
       x = "Height Class (m)", 
       y = "Error", 
       fill = "Height class") +
  facet_wrap(~Metric, scales = "free", ncol = 2) +  # Facet by Metric
  theme_minimal()  # Minimal theme for a clean look
```








