---
title: "Untitled"
author: "abbey yatsko"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(here)
library(ggplot2)
```

load data - TLS wood volume 
```{r}
# read in list of csvs
files <- list.files(path = "~/Desktop/Arbor_Meta/FireBreak_new/GitHub/repos/savanna/data/TLS_plot_CSVs", pattern = "AM.*\\.csv$", full.names = TRUE)
df_list <- lapply(files, read.csv)

# combine list of dataframes into one dataframe
tls_wv <- do.call(rbind, df_list)

# create new column for plot number - select everything in the string before the . 
tls_wv$plot_id <- sub("\\..*", "", tls_wv$ID)

# select everything in the string after the . 
tls_wv$tree_id <- sub(".*\\.", "", tls_wv$ID)

# write.csv(tls_wv, "data/data_out/TLS_wood_vol.csv", row.names = FALSE)

# summarize woody volume at the plot level 
TLS_wv <- tls_wv %>%
  group_by(plot_id) %>%
  summarise(X_mean = mean(Volume..L.),
            X_sum = sum(Volume..L.))
```

load data - ALS and CNN shade volume
```{r}
ALS_sv <- read.csv("~/Desktop/Arbor_Meta/FireBreak_new/GitHub/repos/savanna/data/ALS_shade_vol_Zonal_stats.csv")
CNN_sv <- read.csv("~/Desktop/Arbor_Meta/FireBreak_new/GitHub/repos/savanna/data/Model_shade_vol_Zonal_stats.csv")
```

Convert canopy heights to shade volume 
```{r}
ALS_sv$X_mean_sv <- ALS_sv$X_mean
ALS_sv$X_sum_sv <- ALS_sv$X_sum
ALS_sv$method <- "ALS"

CNN_sv$X_mean_sv <- CNN_sv$X_mean
CNN_sv$X_sum_sv <- CNN_sv$X_sum
CNN_sv$method <- "CNN"

CNN_mean <- CNN_sv$X_mean_sv
ALS_mean <- ALS_sv$X_mean_sv

CNN_sum <- CNN_sv$X_sum
ALS_sum <- ALS_sv$X_sum

x <- as.data.frame(cbind(CNN_mean, ALS_mean))
y <- as.data.frame(cbind(CNN_sum, ALS_sum))

# relationship between ALS and CNN shade volume
ggplot(x, aes(x = CNN_mean, y = ALS_mean)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") 

# relationship between ALS and CNN shade volume
ggplot(y, aes(x = CNN_sum, y = ALS_sum)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") 

# linear regression 
mod <- lm(CNN_mean ~ ALS_mean, data = x)
summary(mod)

```

Calculate coefficient relating woody volume to shade volume
```{r}
# TLS woody volume 
colnames(TLS_wv)[2] <- "TLS_mean"
colnames(TLS_wv)[3] <- "TLS_sum"

# ALS shade volume
ALS_sv_sum <- ALS_sv[, c("proj", "X_mean_sv", "X_sum_sv", "plot_area")]
colnames(ALS_sv_sum)[1] <- "plot_id"
colnames(ALS_sv_sum)[2] <- "ALS_mean"
colnames(ALS_sv_sum)[3] <- "ALS_sum"

# CNN shade volume
CNN_sv_sum <- CNN_sv[, c("proj", "X_mean_sv", "X_sum_sv")]
colnames(CNN_sv_sum)[1] <- "plot_id"
colnames(CNN_sv_sum)[2] <- "CNN_mean"
colnames(CNN_sv_sum)[3] <- "CNN_sum"

# merge dataframes by plot_id
df <- merge(TLS_wv, ALS_sv_sum, by = "plot_id")
df <- merge(df, CNN_sv_sum, by = "plot_id")

df$TLS_sum_m3 <- df$TLS_sum / 1000

df$TLS_sum_1m2 <- df$TLS_sum_m3 / df$plot_area
df$ALS_sum_1m2 <- df$ALS_sum / df$plot_area

# relationship between ALS and CNN shade volume
ggplot(df, aes(x = CNN_mean, y = ALS_mean)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(x = "CNN Shade Volume (m^3)", y = "ALS Shade Volume (m^3)") +
  theme_classic()

# relationship between CNN shade volume and TLS woody volume
ggplot(df, aes(x = CNN_mean, y = TLS_mean)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "CNN Shade Volume (m^3)", y = "TLS Woody Volume (m^3)") +
  theme_classic()

# relationship between ALS shade volume and TLS woody volume
ggplot(df, aes(x = ALS_sum_1m2, y = TLS_sum_1m2)) + 
  geom_point() +
  theme_classic()+
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "ALS Shade Volume (m^3)", y = "TLS Woody Volume (m^3)") +
  theme(plot.title = element_text(hjust = 0.5))  
  #geom_text(aes(label = plot_id), nudge_x = 0, nudge_y = 0.1, check_overlap = FALSE)

# Coefficient: WV (TLS): SV (ALS)
mod <- lm(TLS_sum_1m2 ~ ALS_sum_1m2, data = df)
summary(mod)

# Coefficient: WV (TLS): SV (CNN)
mod <- lm(TLS_mean ~ CNN_mean, data = df)
summary(mod)
```

troubleshooting with coefficient 
```{r}
cal <- read.csv("/Users/abbeyyatsko/Downloads/callitris.csv")

# merge cal and df by plot_id
df <- merge(df, cal, by = "plot_id")

ggplot(df, aes(x = ALS_sum, y = TLS_sum, color = contains_callitris)) + 
  geom_point() +
  theme_classic()+
  facet_wrap(~contains_callitris) + 
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "ALS Shade Volume (m^3)", y = "TLS Woody Volume (m^3)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_text(aes(label = plot_id), nudge_x = 0, nudge_y = 0.1, check_overlap = FALSE)

mod <- lm(TLS_sum ~ CNN_sum, data = df[df$contains_callitris == "y",])
summary(mod)

mod <- lm(TLS_sum ~ CNN_sum, data = df[df$contains_callitris == "n",])

```

lachy coefficient biz 
```{r}
lachy <- read.csv("/Users/abbeyyatsko/Downloads/Grenfell_data.csv")

ggplot(lachy, aes(x = NN_predicted_shade_vol_L, y = Tree_cylinder_vol_L)) + 
  geom_point() +
  theme_classic()+
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "ALS Shade Volume (m^3)", y = "TLS Woody Volume (m^3)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_text(aes(label = plot_id), nudge_x = 0, nudge_y = 0.1, check_overlap = FALSE)

mod <- lm(Tree_cylinder_vol_L ~ NN_predicted_shade_vol_L, data = lachy)
summary(mod)
```

